
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['awtl-backend-clusterip:80']
        labels:
          application: 'backend'