apiVersion: apps/v1
kind: Deployment
metadata:
  name: awtl-frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awtl-frontend
  template:
    metadata:
      labels:
        app: awtl-frontend
    spec:
      containers:
      - name: awtl-frontend
        image: myherik/awtl-frontend:latest
        ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: awtl-frontend-clusterip
spec:
  type: ClusterIP
  selector:
    app: awtl-frontend
  ports:
    - name: awtl-frontend
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: awtl-frontend-np-srv
spec:
  type: NodePort
  selector:
    app: awtl-frontend
  ports:
    - name: awtl-frontend
      protocol: TCP
      port: 80
      targetPort: 80