version: '3'

volumes:
  postgres_data:
    driver: local

services: 
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_example
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  redis:
    image: s341833/redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: redispassword
  prometheus:
    image: 'prom/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.2.0
    container_name: grafana
    ports:
        - 3000:3000
    depends_on:
        - "prometheus"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80
    depends_on:
      - "grafana"
      - "prometheus"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  keycloak:
    build: .
    container_name: keycloak
    ports:
      - 8081:8080
    depends_on: 
      - postgres
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
      PROXY_ADDRESS_FORWARDING: true
  frontend:
    image: s341833/awtl-frontend
    