version: '3.7'
services: 
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_example
  redis:
    image: s341833/redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: redispassword