version: '3.7'

volumes:
  postgres_data:
    driver: local
services: 
  prometheus:
    image: 'prom/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  nginx:
    image: s341833/awtl-nginx
    container_name: nginx
    ports: 
      - 80:80
      - 3002:3002
    depends_on:
      - "prometheus"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  keycloak:
#    build: .
    image: s341833/awtl-keycloak
    container_name: keycloak
    ports:
      - 8081:8080
#    volumes:
#      - ./keycloak/config/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
#      - ./keycloak/themes:/opt/jboss/keycloak/themes:rw
    depends_on: 
      - postgres
    environment:
      KEYCLOAK_WELCOME_THEME: met
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
      PROXY_ADDRESS_FORWARDING: 'true'
  frontend:
    image: s341833/awtl-frontend
    