name: Docker Image CI Frontend

on:
  push:
    branches: [ master ]
    paths:
      - "Frontend - awtls/**"
  pull_request:
    branches: [ master ]

jobs:

  build-frontend: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: "./Frontend - awstl/"
        push: true
        tags: s341833/awtl-frontend:latest